
plugins {
    id 'com.android.application' version '8.1.0' apply false
    id 'com.android.library' version '8.1.0' apply false
    id 'org.jetbrains.kotlin.android' version '1.8.20' apply false
}

allprojects {
    repositories {
        google()        // Repositório principal para bibliotecas Android
        mavenCentral()  // Repositório para bibliotecas Java/Kotlin comuns
    }
}

// 3. Configurações de Task: Otimiza o build para o ambiente do GitHub
tasks.register('clean', Delete) {
    description = 'Deleta o diretório de build do projeto.'
    delete rootProject.buildDir
}
